name: copy_paste_media
description: Copy and paste images to and from the system clipboard in Flutter.
version: 0.1.0
homepage: https://github.com/rutvik110/copy_paste_media
repository: https://github.com/rutvik110/copy_paste_media
issue_tracker: https://github.com/rutvik110/copy_paste_media/issues

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - clipboard
  - copy-paste
  - macos
  - desktop
  - image

platforms:
  macos:

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: CopyPasteMediaPlugin
